### ISSUE TITLE
gl.read.dart warning message to use keepNA = TRUE irrelevant

### ISSUE THREAD

**Issue by stiatragul** [green-striped-gecko/dartR#666]
Hello dartR devs, 

Writing to report that when I tried to read in a file and metadata with missing population information I get a warning message:

```
 1: There are individuals with missing population information in the data set. If you want to retain these, use the option `keepNA = TRUE`. 
```

However when I tried 

```
t1_2 <- dartR.base::gl.read.dart(
    filename = "Report_XXXXX_SNP_mapping_2.csv",
    ind.metafile = "Metadata.csv",
    keepNA = TRUE,
    probar = F,
)
```

I got an error

```
Error in dartR.base::gl.read.dart(filename = "Report_XXXXX_SNP_mapping_2.csv",  : 
  unused argument (keepNA = TRUE)
```

**Comment by mijangos81** [comment]
Hi Putter,

Thanks for reporting this issue. 

That warning message comes from the function seppop from package adegenet. However, I could not replicate the error and I could not find where the seppop function is used in gl.read.dart. 

Could you please let us know what version of dartR are you using? Maybe you can send us the information that is printed from the function: sessionInfo()

Cheers,
Luis

**Comment by stiatragul** [comment]
No problem @mijangos81 

```
R version 4.4.2 (2024-10-31)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.5 LTS

Matrix products: default
BLAS/LAPACK: /home/computer1/.conda/envs/ausarg/lib/libopenblasp-r0.3.27.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C               LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8     LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8    LC_PAPER=en_AU.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

time zone: Australia/Sydney
tzcode source: system (glibc)

attached base packages:
[1] grid      tools     stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] purrr_1.0.2           gridExtra_2.3         viridis_0.6.5         viridisLite_0.4.2     pheatmap_1.0.12       stringr_1.5.1         data.table_1.16.4     related_1.0           dartR.sexlinked_1.0.5 dartR.captive_0.75    dartR.popgen_1.0.0   
[12] dartR.sim_0.70        dartR.base_0.98       dartR.data_1.0.8      dplyr_1.1.4           ggplot2_3.5.1         adegenet_2.1.10       ade4_1.7-22           dartRverse_1.0.5     

loaded via a namespace (and not attached):
  [1] splines_4.4.2       later_1.4.1         polspline_1.1.25    bitops_1.0-9        fields_16.3         tibble_3.2.1        HardyWeinberg_1.7.8 rpart_4.1.23        lifecycle_1.0.4     Rdpack_2.6.2        doParallel_1.0.17   Rsolnp_1.16        
 [13] haplo.stats_1.9.7   globals_0.16.3      lattice_0.22-6      MASS_7.3-61         backports_1.5.0     magrittr_2.0.3      Hmisc_5.2-2         rmarkdown_2.29      remotes_2.5.0       httpuv_1.6.15       spam_2.11-1         sessioninfo_1.2.2  
 [25] pkgbuild_1.4.6      SNPassoc_2.1-2      minqa_1.2.8         RColorBrewer_1.1-3  multcomp_1.4-28     maps_3.4.2.1        pkgload_1.4.0       gdsfmt_1.40.2       RCurl_1.98-1.16     nnet_7.3-19         TH.data_1.1-3       sandwich_3.1-1     
 [37] poisbinom_1.0.1     listenv_0.9.1       vegan_2.6-10        MatrixModels_0.5-3  parallelly_1.42.0   StAMPP_1.6.3        permute_0.9-7       codetools_0.2-20    tidyselect_1.2.1    shape_1.4.6.1       farver_2.1.2        lme4_1.1-36        
 [49] base64enc_0.1-3     jsonlite_1.8.9      mitml_0.4-5         ellipsis_0.3.2      Formula_1.2-5       survival_3.7-0      iterators_1.0.14    systemfonts_1.2.1   foreach_1.5.2       SNPRelate_1.38.1    Rcpp_1.0.14         glue_1.8.0         
 [61] pan_1.9             xfun_0.50           mgcv_1.9-1          usethis_3.1.0       withr_3.0.2         fastmap_1.2.0       boot_1.3-30         SparseM_1.84-2      caTools_1.18.3      truncnorm_1.0-9     digest_0.6.37       R6_2.5.1           
 [73] mime_0.12           mice_3.17.0         colorspace_2.1-1    gtools_3.9.5        utf8_1.2.4          tidyr_1.3.1         generics_0.1.3      httr_1.4.7          htmlwidgets_1.6.4   pkgconfig_2.0.3     gtable_0.3.6        httpgd_2.0.2       
 [85] furrr_0.3.1         htmltools_0.5.8.1   profvis_0.4.0       dotCall64_1.2       scales_1.3.0        reformulas_0.4.0    ggdendro_0.2.0      knitr_1.49          rstudioapi_0.17.1   reshape2_1.4.4      checkmate_2.3.2     nlme_3.1-165       
 [97] nloptr_2.1.1        cachem_1.1.0        zoo_1.8-12          KernSmooth_2.23-24  parallel_4.4.2      miniUI_0.1.1.1      foreign_0.8-87      pillar_1.10.1       vctrs_0.6.5         gplots_3.2.0        urlchecker_1.0.1    promises_1.3.2     
[109] jomo_2.7-6          xtable_1.8-4        cluster_2.1.6       htmlTable_2.4.3     evaluate_1.0.3      mvtnorm_1.3-3       cli_3.6.3           compiler_4.4.2      rlang_1.1.5         crayon_1.5.3        rms_7.0-0           labeling_0.4.3     
[121] plyr_1.8.9          fs_1.6.5            stringi_1.8.4       arsenal_3.6.3       unigd_0.1.2         munsell_0.5.1       devtools_2.4.5      glmnet_4.1-8        quantreg_6.00       Matrix_1.7-1        patchwork_1.3.0     future_1.34.0      
[133] pegas_1.3           seqinr_4.2-36       shiny_1.10.0        rbibutils_2.3       igraph_2.0.3        broom_1.0.7         memoise_2.0.1       ape_5.8-1     
```

**Comment by mijangos81** [comment]
Hi Putter,

I think this has been solved in the latest version of the developing branch of dartR.base (Version: 1.0.0).

Could you please try installing this latest version (see command below) and give it a try?

> devtools::install_github("green-striped-gecko/dartR.base@dev")

There are two issues that might cause the installation to fail; see the link below with instructions on how to solve them:
https://groups.google.com/g/dartr/c/Bc4aT7GmHjs/m/ZYBQ_ekaEgAJ 

Cheers,
Luis

**Comment by stiatragul** [comment]
Hey Luis, 

I'm still getting the same error with the dev branch of dartR.base installed.

```
R version 4.4.2 (2024-10-31)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.5 LTS

Matrix products: default
BLAS/LAPACK: /home/computer1/.conda/envs/ausarg/lib/libopenblasp-r0.3.27.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C               LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8     LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8    LC_PAPER=en_AU.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

time zone: Australia/Sydney
tzcode source: system (glibc)

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] purrr_1.0.2           gridExtra_2.3         pheatmap_1.0.12       stringr_1.5.1         data.table_1.16.4     dartR.sexlinked_1.0.5 dartR.captive_0.75    dartR.popgen_1.0.0    dartR.sim_0.70        dartR.base_1.0.0      dartR.data_1.0.8     
[12] dplyr_1.1.4           ggplot2_3.5.1         adegenet_2.1.10       ade4_1.7-22           dartRverse_1.0.5     

loaded via a namespace (and not attached):
  [1] RColorBrewer_1.1-3 ggdendro_0.2.0     rstudioapi_0.17.1  jsonlite_1.8.9     magrittr_2.0.3     TH.data_1.1-3      farver_2.1.2       rmarkdown_2.29     fs_1.6.5           fields_16.3        vctrs_0.6.5        memoise_2.0.1     
 [13] SNPRelate_1.38.1   RCurl_1.98-1.16    base64enc_0.1-3    htmltools_0.5.8.1  usethis_3.1.0      polspline_1.1.25   curl_6.2.0         Formula_1.2-5      parallelly_1.42.0  htmlwidgets_1.6.4  plyr_1.8.9         sandwich_3.1-1    
 [25] zoo_1.8-12         SNPassoc_2.1-2     cachem_1.1.0       igraph_2.0.3       mime_0.12          lifecycle_1.0.4    iterators_1.0.14   pkgconfig_2.0.3    Matrix_1.7-1       R6_2.5.1           fastmap_1.2.0      future_1.34.0     
 [37] shiny_1.10.0       digest_0.6.37      colorspace_2.1-1   furrr_0.3.1        patchwork_1.3.0    pkgload_1.4.0      Hmisc_5.2-2        vegan_2.6-10       httr_1.4.7         mgcv_1.9-1         compiler_4.4.2     remotes_2.5.0     
 [49] withr_3.0.2        doParallel_1.0.17  htmlTable_2.4.3    backports_1.5.0    pkgbuild_1.4.6     maps_3.4.2.1       MASS_7.3-61        quantreg_6.00      sessioninfo_1.2.2  permute_0.9-7      gdsfmt_1.40.2      tools_4.4.2       
 [61] foreign_0.8-87     ape_5.8-1          httpuv_1.6.15      nnet_7.3-19        glue_1.8.0         nlme_3.1-165       promises_1.3.2     checkmate_2.3.2    cluster_2.1.6      reshape2_1.4.4     generics_0.1.3     seqinr_4.2-36     
 [73] gtable_0.3.6       poisbinom_1.0.1    tidyr_1.3.1        foreach_1.5.2      pillar_1.10.1      spam_2.11-1        later_1.4.1        splines_4.4.2      lattice_0.22-6     survival_3.7-0     SparseM_1.84-2     tidyselect_1.2.1  
 [85] httpgd_2.0.2       rms_7.0-0          miniUI_0.1.1.1     knitr_1.49         xfun_0.50          devtools_2.4.5     stringi_1.8.4      unigd_0.1.2        evaluate_1.0.3     codetools_0.2-20   tibble_3.2.1       cli_3.6.3         
 [97] rpart_4.1.23       xtable_1.8-4       systemfonts_1.2.1  munsell_0.5.1      Rcpp_1.0.14        pegas_1.3          globals_0.16.3     haplo.stats_1.9.7  StAMPP_1.6.3       parallel_4.4.2     MatrixModels_0.5-3 ellipsis_0.3.2    
[109] dotCall64_1.2      arsenal_3.6.3      profvis_0.4.0      urlchecker_1.0.1   bitops_1.0-9       listenv_0.9.1      viridisLite_0.4.2  mvtnorm_1.3-3      scales_1.3.0       crayon_1.5.3       rlang_1.1.5        multcomp_1.4-28  
```

**Comment by mijangos81** [comment]
Thanks Putter! 

That's weird, could you please send me a subset of your dataset and metadata to my mail (luis.mijangos@gmail.com) so I can reproduce the error?

Luis

**Comment by stiatragul** [comment]
Hey Luis, 

I think I figured it out, this error only shows up when blanks in the pop column is coded as `NA`. If it's actually blank then the error doesn't show!
